FROM fedora:24
MAINTAINER Fridolin Pokorny <fpokorny@redhat.com>
ENV LANG=en_US.utf8

RUN groupadd worker && useradd --create-home --home-dir /home/worker -g worker worker

RUN dnf install -y git make graphviz python3-psycopg2

COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

# Set up Selinonlib and Selinon
RUN pip3 install -U git+https://github.com/fridex/selinonlib && \
 pip3 install -U git+https://github.com/fridex/selinon

# We use additional storages that are not listed in requirements.txt explicitly
RUN pip3 install pymongo SQLAlchemy SQLAlchemy-Utils

# Use volume
WORKDIR /home/worker/worker
USER worker

ENTRYPOINT ["celery"]
CMD ["worker", "--app=tasks", "-l", "INFO", "--concurrency=1"]
